apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: devsecops-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-webapp
  template:
    metadata:
      labels:
        app: devsecops-webapp
    spec:
      containers:
        - name: webapp
          image: devsecops-webapp:1.0
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: devsecops-webapp
  ports:
    - name: http
      port: 5000
      targetPort: 5000
