# deploy_modsecurity.yml
# Playbook Ansible pour installer et configurer ModSecurity sur Minikube

- name: Déploiement de ModSecurity (WAF) sur Minikube
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Vérifier la connexion locale
      ansible.builtin.ping:

    - name: Lancer le conteneur ModSecurity (OWASP CRS)
      community.docker.docker_container:
        name: modsecurity-waf
        image: owasp/modsecurity-crs:nginx
        state: started
        restart_policy: always
        ports:
          - "8081:80"
